### ISSUE TITLE
Can not be builded with XCode 12

### ISSUE THREAD

**Issue by fboulegue** [craft-of-the-mines/Raptor#6]
Hey it seem there is a problem with XCode 12 after importing the Package via Swift Package Manager.
Would be great if you could check it as its the only RCON Lib for Swift

![warning](https://user-images.githubusercontent.com/2719590/90480444-88eaf200-e130-11ea-919e-de5de29fa10b.PNG)

**Comment by fboulegue** [comment]
seem to be part of


`The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions`
![unknown](https://user-images.githubusercontent.com/2719590/90483356-e123f300-e134-11ea-95c9-456e01a63193.png)

**Comment by rpwachowski** [comment]
Hi @fboulegue, I opened #7 to resolve the issue you were having. Seems that in Xcode 12 the compiler is a bit less tolerant when evaluating literal expressions.

**Comment by trister1997** [comment]
#7 Has been merged. Closing issue :)
